# Generated by Django 5.0.8 on 2025-01-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
