# Generated by Django 5.0.8 on 2025-01-14 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_image_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image_url",
            new_name="image",
        ),
    ]
